sudo: false # We want container builds.

language: python
python:
  - "2.7"
node_js:
  - "0.10"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: PYPY_VERSION="4.0.1" NO_COVERAGE="1"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads
services:
  - redis-server

before_install:
  # If necessary, set up an appropriate version of pypy.
  - if [ ! -z "$PYPY_VERSION" ]; then source utils/setup-pypy-travis.sh; fi
  - if [ ! -z "$PYPY_VERSION" ]; then python --version 2>&1 | fgrep "PyPy $PYPY_VERSION"; fi
install:
  # Update pip because Travis has 6.x which doesn't cache wheels
  - "pip install pip>=8.0.0"
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=vxsandbox"; else COVERAGE_CMD=""; fi
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" $COVERAGE_CMD `which trial` vxsandbox

after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
