language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: NO_COVERAGE="1"
services:
  - redis-server
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=vxsandbox"; else COVERAGE_CMD=""; fi
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" $COVERAGE_CMD `which trial` vxsandbox
after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
