sudo: false # We want container builds.

language: python
python:
  - "2.7"
node_js:
  - "0.10"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: PYPY_VERSION="5.3.1" NO_COVERAGE="1"

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
services:
  - redis-server

before_install:
  # If necessary, set up an appropriate version of pypy.
  - |
      if [[ -n "$PYPY_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pypy/releases/download/0.1.0/setup-pypy.sh
        source setup-pypy.sh
      fi
  # Upgrade pip to make sure we get wheel caching
  - pip install --upgrade pip

install:
  - pip install -e .
  - if [[ -z "$NO_COVERAGE" ]]; then pip install coveralls; fi

script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_CMD="coverage run --source=vxsandbox"; else COVERAGE_CMD=""; fi
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" $COVERAGE_CMD "$(which trial)" vxsandbox

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then coveralls; fi
