# Default (xenial) has antique openssl that cryptography no longer supports.
dist: focal

language: python
python:
  - "2.7"
env:
  - NODEJS_VERSION="0.10"  # Ubuntu 14.04 / Debian 8 packages
  - NODEJS_VERSION="4.5.0" # LTS release
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - env: PYENV_VERSION="pypy2.7-7.3.0" NO_COVERAGE="1" NODEJS_VERSION="4.5.0"

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
services:
  - redis-server

before_install:
  # If necessary, set up an appropriate version of pypy.
  - |
      export PYENV_ROOT=$HOME/.travis-pyenv
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
  # Upgrade pip to make sure we get wheel caching
  - pip install --upgrade pip
  # NodeJS
  - nvm install $NODEJS_VERSION

install:
  - pip install -e .
  - if [[ -z "$NO_COVERAGE" ]]; then pip install coveralls; fi

script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_CMD="coverage run --source=vxsandbox"; else COVERAGE_CMD=""; fi
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" $COVERAGE_CMD "$(which trial)" vxsandbox

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then coveralls; fi
